namespace AZ.Generator.EntityFrameworkCore.Constants;

internal static class Attributes
{
	public const string EntitySets = "EntitySetsAttribute";

	public const string EntitySetConfig = "EntitySetConfigAttribute";

	internal const string EntitySetConfig_Name = "Name";

	internal const string EntitySetConfig_Ignore = "Ignore";

	internal const string EntitySetsDefinition =
		$$"""
		// <auto-generated />
		
		namespace {{Namespaces.Attributes}};
		
		[Microsoft.CodeAnalysis.EmbeddedAttribute]
		[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
		internal sealed class {{EntitySets}} : System.Attribute
		{
			public System.Type[] ContainingTypes { get; }

			public {{EntitySets}}(params System.Type[] containingTypes)
			{
				ContainingTypes = containingTypes;
			}
		}

		""";

	internal const string EntitySetConfigDefinition =
		$$"""
		// <auto-generated />
		#nullable enable

		namespace {{Namespaces.Attributes}};
		
		[Microsoft.CodeAnalysis.EmbeddedAttribute]
		[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
		internal sealed class {{EntitySetConfig}} : System.Attribute
		{
			public string {{EntitySetConfig_Name}} { get; set; } = string.Empty;

			public bool {{EntitySetConfig_Ignore}} { get; set; } = false;
		}

		""";
}
