//HintName: DiscriminatedUnionMemberAttribute.g.cs
namespace AZ.Generator.Functional.Attributes;
// <auto-generated />
#nullable enable

[Microsoft.CodeAnalysis.EmbeddedAttribute]
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal sealed class DiscriminatedUnionMemberAttribute : System.Attribute
{
	public string? ArgumentName { get; set; }

	public string? IsMethodName { get; set; }
}
