//HintName: DiscriminatedUnionAttribute.g.cs
// <auto-generated />

namespace AZ.Generator.Functional.Attributes;

[Microsoft.CodeAnalysis.EmbeddedAttribute]
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal sealed class DiscriminatedUnionAttribute : System.Attribute;
