//HintName: TestDbContextEntitySets.g.cs
// <auto-generated />
#nullable enable

namespace Foo;

partial class TestDbContext
{
	public Microsoft.EntityFrameworkCore.DbSet<global::Foo.Entities.EntityOne> EntityOne { get; private set; }
	public Microsoft.EntityFrameworkCore.DbSet<global::Foo.Entities.EntityTwo> EntityTwo { get; private set; }
}

