//HintName: EntityConfigurationsAttribute.g.cs
// <auto-generated />

namespace AZ.Generator.EntityFrameworkCore.Attributes;

[Microsoft.CodeAnalysis.EmbeddedAttribute]
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal sealed class EntityConfigurationsAttribute : System.Attribute
{
	public System.Type[] ContainingTypes { get; }

	public EntityConfigurationsAttribute(params System.Type[] containingTypes)
	{
		ContainingTypes = containingTypes;
	}
}
