//HintName: TestDbContextEntityConfigurations.g.cs
// <auto-generated />
#nullable enable

namespace Foo;

partial class TestDbContext
{
	private void ApplyEntityConfigurations(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
	{
		modelBuilder.ApplyConfiguration(global::AZ.Generator.EntityFrameworkCore.Configurations.TestDbContextConfigurations.Foo_Configurations_EntityOneConfiguration);
		modelBuilder.ApplyConfiguration(global::AZ.Generator.EntityFrameworkCore.Configurations.TestDbContextConfigurations.Foo_Configurations_EntityTwoConfiguration);
	}
}

