//HintName: EntityConfiguration.g.cs
// <auto-generated />
#nullable enable

namespace AZ.Generator.EntityFrameworkCore.Attributes;

[Microsoft.CodeAnalysis.EmbeddedAttribute]
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal sealed class EntityConfiguration : System.Attribute
{
	public bool Ignore { get; set; } = false;
}
