//HintName: EntitySetAttribute.g.cs
// <auto-generated />
#nullable enable

namespace AZ.Generator.EntityFrameworkCore.Attributes;

[Microsoft.CodeAnalysis.EmbeddedAttribute]
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal sealed class EntitySetAttribute : System.Attribute
{
	public string Name { get; set; } = string.Empty;

	public bool Ignore { get; set; } = false;
}
