//HintName: TestDbContextConfigurations.g.cs
// <auto-generated />
#nullable enable

namespace AZ.Generator.EntityFrameworkCore.Configurations;

internal static class TestDbContextConfigurations
{
	internal static readonly global::Foo.Configurations.EntityOneConfiguration Foo_Configurations_EntityOneConfiguration = new();
	internal static readonly global::Foo.Configurations.EntityTwoConfiguration Foo_Configurations_EntityTwoConfiguration = new();
}

