//HintName: EntitySetsAttribute.g.cs
// <auto-generated />

namespace AZ.Generator.EntityFrameworkCore.Attributes;

[Microsoft.CodeAnalysis.EmbeddedAttribute]
[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
internal sealed class EntitySetsAttribute : System.Attribute
{
	public System.Type ContainingType { get; }

	public EntitySetsAttribute(System.Type containingType)
	{
		ContainingType = containingType;
	}
}
