//HintName: TestDbContextEntityConfigurations.g.cs
// <auto-generated />
#nullable enable

namespace Foo;

partial class TestDbContext
{
	protected override void OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);

		modelBuilder.ApplyConfiguration(global::AZ.Generator.EntityFrameworkCore.Configurations.TestDbContextConfigurations.Foo_Configurations_EntityOneConfiguration);

		OnModelCreatingPartial(modelBuilder);
	}

	partial void OnModelCreatingPartial(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder);
}

