namespace AZ.Generator.Functional.Constants;

internal static class Attributes
{
	public const string DiscriminatedUnion = "DiscriminatedUnionAttribute";

	public const string DiscriminatedUnionMember = "DiscriminatedUnionMemberAttribute";

	public const string DiscriminatedUnionMember_ArgumentName = "ArgumentName";

	public const string DiscriminatedUnionMember_IsMethodName = "IsMethodName";

	internal const string DiscriminatedUnionDefinition =
		$$"""
		// <auto-generated />

		namespace {{Namespaces.Attributes}};

		[Microsoft.CodeAnalysis.EmbeddedAttribute]
		[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
		internal sealed class {{DiscriminatedUnion}} : System.Attribute;

		""";

	internal const string DiscriminatedUnionMemberDefinition =
		$$"""
		namespace {{Namespaces.Attributes}};
		// <auto-generated />
		#nullable enable

		[Microsoft.CodeAnalysis.EmbeddedAttribute]
		[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
		internal sealed class {{DiscriminatedUnionMember}} : System.Attribute
		{
			public string? {{DiscriminatedUnionMember_ArgumentName}} { get; set; }

			public string? {{DiscriminatedUnionMember_IsMethodName}} { get; set; }
		}
		
		""";
}
